service: website

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-central-1

plugins:
  - serverless-finch

custom:
  client:
    bucketName: house-of-lola-test2-${self:provider.stage}
    distributionFolder: build
    indexDocument: index.html
    errorDocument: index.html
